mobilizon:
  host: mobilizon.example.org
  secretKeyBase: ci-only-secret-key-base-ci-only-secret-key-base-ci-only-secret-key-base
  secretKey: ci-only-secret-key-ci-only-secret-key-ci-only-secret-key
database:
  password: ci-only
oidc:
  clientSecret: ci-only-client-secret
dex:
  enabled: true
  staticPasswords:
    - email: admin@example.org
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: admin
      userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
