mobilizon:
  host: mobilizon.example.org
  existingSecret: mobilizon-keys
postgresql:
  enabled: false
database:
  host: mobilizon-db-rw
  existingSecret: mobilizon-db-app
  secretKeys:
    username: username
smtp:
  enabled: true
  host: smtp.example.org
  existingSecret: mobilizon-smtp
ingress:
  enabled: true
  tlsSecretName: mobilizon-tls
httpRoute:
  enabled: true
  parentRefs:
    - name: gateway
