{{- $instance := not .Values.mobilizon.existingSecret }}
{{- $database := not .Values.database.existingSecret }}
{{- $smtp := and .Values.smtp.enabled (not .Values.smtp.existingSecret) .Values.smtp.password }}
{{- if or $instance $database $smtp }}
{{- $current := (lookup "v1" "Secret" .Release.Namespace (include "mobilizon.fullname" .)).data | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mobilizon.fullname" . }}
  labels:
    {{- include "mobilizon.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $instance }}
  secret-key-base: {{ index $current "secret-key-base" | default (randAlphaNum 64 | b64enc) }}
  secret-key: {{ index $current "secret-key" | default (randAlphaNum 64 | b64enc) }}
  {{- end }}
  {{- if $database }}
  database-password: {{ .Values.database.password | b64enc | default (index $current "database-password") | default (randAlphaNum 32 | b64enc) }}
  {{- end }}
  {{- if $smtp }}
  smtp-password: {{ .Values.smtp.password | b64enc }}
  {{- end }}
{{- end }}
